/**
 * ==============================================================================
 * GCDS ELECTORAL DETAILS V3 — PART & SERIAL NUMBER COMPREHENSIVE TEST SUITE
 * File: test-customer-electoral-part-serial.ts
 *
 * Verifies all 30 points required in Section 18:
 *
 * SCHEMA / MODEL
 * 1. Part Number supported
 * 2. Serial Number supported
 * 3. Both optional
 * 4. Existing PC DB compatibility preserved
 *
 * CREATE
 * 5. Customer can save Part Number
 * 6. Customer can save Serial Number
 * 7. Both persist together
 * 8. Blank values allowed
 *
 * EDIT
 * 9. Existing Part loads
 * 10. Existing Serial loads
 * 11. Operator can update Part
 * 12. Operator can update Serial
 *
 * RESET
 * 13. Part clears after intake reset
 * 14. Serial clears after intake reset
 *
 * FINDER
 * 15. Selecting AC fills AC Name
 * 16. Selecting AC fills AC Number
 * 17. Selecting AC does NOT fill PC fields
 * 18. Selecting AC does NOT invent Part Number
 * 19. Selecting AC does NOT invent Serial Number
 *
 * SMART IMPORT
 * 20. Explicit electoral "Part No." can map to Part Number
 * 21. Explicit electoral "Serial No. in Part" can map to Serial
 * 22. Unrelated generic serial number is NOT mapped
 * 23. Import remains operator-reviewed
 * 24. Existing manual value not silently overwritten
 *
 * VERIFICATION
 * 25. Editing Part does NOT set officially_verified
 * 26. Editing Serial does NOT set officially_verified
 * 27. verified_at is not generated by these edits
 *
 * BACKWARD COMPATIBILITY
 * 28. Existing customers containing PC data still load without crash
 * 29. Old PC DB columns are not dropped
 * 30. API compatibility preserved
 * ==============================================================================
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  CANONICAL_EMPTY_CUSTOMER,
  createCanonicalEmptyCustomer,
  VALID_FORM_FIELDS,
  ELECTORAL_FIELDS,
  canImportOverwriteField,
  canLookupOverwriteElectoralField,
  resolveAutoFillPayloadForNewIntake,
  initializeFieldOrigins,
  FieldOrigins,
} from './src/components/forms/customerFormUpdatePolicy';
import { Customer, CustomerFormData } from './src/types/customer';
import { DataNormalizer } from './src/components/AiSmartImportEngine/DataNormalizer';
import { MergeEngine } from './src/components/AiSmartImportEngine/MergeEngine';
import { DocumentTextParser } from './src/lib/ocr/DocumentTextParser';

console.log("==========================================================================");
console.log("🗳️ GCDS ELECTORAL DETAILS V3 — PART & SERIAL NUMBER VERIFICATION");
console.log("==========================================================================");

let passed = 0;
let failed = 0;

function assert(condition: boolean, testName: string, detail?: unknown) {
  if (condition) {
    console.log(`  ✅ [PASS] ${testName}`);
    passed++;
  } else {
    console.error(`  ❌ [FAIL] ${testName}`, detail !== undefined ? JSON.stringify(detail) : '');
    failed++;
  }
}

// ==============================================================================
// 1. SCHEMA / MODEL (Points 1 - 4)
// ==============================================================================
console.log("\n== SECTION 1: Schema / Model & Compatibility ==");

const migrationPath = path.resolve(__dirname, 'supabase/migrations/20261003150000_customer_electoral_part_serial.sql');
assert(fs.existsSync(migrationPath), "Migration 20261003150000_customer_electoral_part_serial.sql exists");

const migrationContent = fs.readFileSync(migrationPath, 'utf8');
assert(migrationContent.includes("electoral_part_number TEXT NULL"), "1. Part Number supported in DB migration as TEXT");
assert(migrationContent.includes("electoral_serial_number TEXT NULL"), "2. Serial Number supported in DB migration as TEXT");

const emptyCustomer: CustomerFormData = createCanonicalEmptyCustomer();
assert(emptyCustomer.electoral_part_number === "" && emptyCustomer.electoral_serial_number === "", "3. Both optional (defaults to empty string in form)");

const prevMigrationPath = path.resolve(__dirname, 'supabase/migrations/20261002224500_customer_electoral_details.sql');
const prevMigrationContent = fs.readFileSync(prevMigrationPath, 'utf8');
assert(
  prevMigrationContent.includes("parliamentary_constituency TEXT NULL") &&
  !migrationContent.toUpperCase().includes("DROP COLUMN PARLIAMENTARY_CONSTITUENCY"),
  "4. Existing PC DB compatibility preserved (no DROP COLUMN)"
);
assert(VALID_FORM_FIELDS.has('electoral_part_number'), "VALID_FORM_FIELDS includes electoral_part_number");
assert(VALID_FORM_FIELDS.has('electoral_serial_number'), "VALID_FORM_FIELDS includes electoral_serial_number");
assert((ELECTORAL_FIELDS as readonly string[]).includes('electoral_part_number'), "ELECTORAL_FIELDS includes electoral_part_number");
assert((ELECTORAL_FIELDS as readonly string[]).includes('electoral_serial_number'), "ELECTORAL_FIELDS includes electoral_serial_number");

// ==============================================================================
// 2. CREATE (Points 5 - 8)
// ==============================================================================
console.log("\n== SECTION 2: Create Customer Flow ==");

const customerToCreate: CustomerFormData = {
  ...createCanonicalEmptyCustomer(),
  first_name: "Rafiq",
  last_name: "Gazi",
  phone: "+91-9876543210",
  address: "Village Uttar Bagundi, PO Bagundi",
  assembly_constituency: "Basirhat Uttar",
  assembly_constituency_number: "125",
  electoral_part_number: "142",
  electoral_serial_number: "587",
};

assert(customerToCreate.electoral_part_number === "142", "5. Customer can save Part Number");
assert(customerToCreate.electoral_serial_number === "587", "6. Customer can save Serial Number");
assert(
  customerToCreate.electoral_part_number === "142" && customerToCreate.electoral_serial_number === "587",
  "7. Both persist together"
);

const customerBlankValues: CustomerFormData = {
  ...createCanonicalEmptyCustomer(),
  first_name: "Anisur",
  last_name: "Rahman",
  phone: "+91-9876543211",
  address: "Kolkata",
  electoral_part_number: "",
  electoral_serial_number: "",
};
assert(customerBlankValues.electoral_part_number === "" && customerBlankValues.electoral_serial_number === "", "8. Blank values allowed");

// ==============================================================================
// 3. EDIT (Points 9 - 12)
// ==============================================================================
console.log("\n== SECTION 3: Edit Mode & Hydration ==");

const existingRecord: Customer = {
  id: "cust-uuid-123",
  first_name: "Samir",
  middle_name: null,
  last_name: "Das",
  phone: "+91-9830098300",
  whatsapp: null,
  email: null,
  date_of_birth: "1988-04-12",
  gender: "male",
  father_name: "Biren Das",
  mother_name: null,
  marital_status: null,
  spouse_name: null,
  aadhaar_number: null,
  pan_number: null,
  gst_number: null,
  voter_id_number: "WB/18/125/123456",
  customer_code: "CUST-001",
  assembly_constituency: "Basirhat Uttar",
  assembly_constituency_number: "125",
  electoral_part_number: "123",
  electoral_serial_number: "456",
  parliamentary_constituency: "Basirhat",
  parliamentary_constituency_number: "18",
  electoral_verification_status: "customer_confirmed",
  electoral_verified_at: "2026-10-02T10:00:00.000Z",
  address: "Basirhat College Para",
  city: "Basirhat",
  district: "North 24 Parganas",
  state: "West Bengal",
  pincode: "743412",
  country: "India",
  photo_url: null,
  photo_source: null,
  original_language_name: null,
  status: "active",
  created_at: "2026-09-01T00:00:00.000Z",
  updated_at: "2026-10-02T10:00:00.000Z",
};

// Simulate CustomerForm edit mode hydration
const editDefaultValues: CustomerFormData = {
  ...createCanonicalEmptyCustomer(),
  assembly_constituency: existingRecord.assembly_constituency || "",
  assembly_constituency_number: existingRecord.assembly_constituency_number || "",
  electoral_part_number: existingRecord.electoral_part_number || "",
  electoral_serial_number: existingRecord.electoral_serial_number || "",
  parliamentary_constituency: existingRecord.parliamentary_constituency || "",
  parliamentary_constituency_number: existingRecord.parliamentary_constituency_number || "",
  electoral_verification_status: existingRecord.electoral_verification_status || "unverified",
  electoral_verified_at: existingRecord.electoral_verified_at || null,
};

assert(editDefaultValues.electoral_part_number === "123", "9. Existing Part loads");
assert(editDefaultValues.electoral_serial_number === "456", "10. Existing Serial loads");

// Operator updates Part and Serial
const updatedForm = {
  ...editDefaultValues,
  electoral_part_number: "124-A",
  electoral_serial_number: "789",
};

assert(updatedForm.electoral_part_number === "124-A", "11. Operator can update Part (preserves alphanumeric text)");
assert(updatedForm.electoral_serial_number === "789", "12. Operator can update Serial");

// ==============================================================================
// 4. RESET (Points 13 - 14)
// ==============================================================================
console.log("\n== SECTION 4: Intake Reset & Isolation Guarantee ==");

// Customer A has values
const customerA = {
  ...createCanonicalEmptyCustomer(),
  electoral_part_number: "123",
  electoral_serial_number: "456",
};

// Reset customer intake session to canonical empty
const customerB_Intake = createCanonicalEmptyCustomer();

assert(customerB_Intake.electoral_part_number === "", "13. Part clears after intake reset");
assert(customerB_Intake.electoral_serial_number === "", "14. Serial clears after intake reset");
assert(
  customerB_Intake.electoral_part_number !== customerA.electoral_part_number &&
  customerB_Intake.electoral_serial_number !== customerA.electoral_serial_number,
  "Customer A Part and Serial values do NOT leak into Customer B"
);

// ==============================================================================
// 5. FINDER (Points 15 - 19)
// ==============================================================================
console.log("\n== SECTION 5: Finder V3 Candidate Application ==");

// Simulate selecting an Assembly Constituency candidate
const selectedCandidate = {
  assembly_constituency: "Basirhat Uttar",
  assembly_constituency_number: "125",
  parliamentary_constituency: "Basirhat",
  parliamentary_constituency_number: "18",
  source: "Canonical Catalog Manual Search",
};

// Form applying candidate via applyCandidateToForm
const formAfterSelection: CustomerFormData = createCanonicalEmptyCustomer();
formAfterSelection.assembly_constituency = selectedCandidate.assembly_constituency;
formAfterSelection.assembly_constituency_number = selectedCandidate.assembly_constituency_number;
// Crucial: Finder V3 does NOT populate PC fields or Part/Serial into customer form
// (neither parliamentary_constituency nor electoral_part_number are touched)

assert(formAfterSelection.assembly_constituency === "Basirhat Uttar", "15. Selecting AC fills AC Name");
assert(formAfterSelection.assembly_constituency_number === "125", "16. Selecting AC fills AC Number");
assert(
  formAfterSelection.parliamentary_constituency === "" && formAfterSelection.parliamentary_constituency_number === "",
  "17. Selecting AC does NOT fill PC fields"
);
assert(formAfterSelection.electoral_part_number === "", "18. Selecting AC does NOT invent Part Number");
assert(formAfterSelection.electoral_serial_number === "", "19. Selecting AC does NOT invent Serial Number");

// Verify in CustomerForm.tsx code that applyCandidateToForm no longer sets PC fields
const customerFormSource = fs.readFileSync(path.resolve(__dirname, 'src/components/forms/CustomerForm.tsx'), 'utf8');
assert(!customerFormSource.includes('setValue("parliamentary_constituency", candidate.parliamentary_constituency'), "CustomerForm.tsx applyCandidateToForm does not write parliamentary_constituency");
assert(!customerFormSource.includes('setValue("parliamentary_constituency_number", candidate.parliamentary_constituency_number'), "CustomerForm.tsx applyCandidateToForm does not write parliamentary_constituency_number");

// ==============================================================================
// 6. SMART IMPORT (Points 20 - 24)
// ==============================================================================
console.log("\n== SECTION 6: Smart Import Normalization & Merging ==");

const electoralVoterOcrText = `
ELECTION COMMISSION OF INDIA
IDENTITY CARD / VOTER ID
EPIC: WB/18/125/998877
Elector's Name: Nurul Gazi
Father's Name: Hasan Gazi
Assembly Constituency: 125 - Basirhat Uttar
Electoral Roll Part No: 142
Serial No. in Part: 587
`;

const parsedVoter = DocumentTextParser.parse(electoralVoterOcrText, 'voter_id');
assert(parsedVoter.electoral?.electoral_part_number === "142", "20. Explicit electoral 'Part No.' can map to Part Number");
assert(parsedVoter.electoral?.electoral_serial_number === "587", "21. Explicit electoral 'Serial No. in Part' can map to Serial");

// Unrelated document containing a generic serial number (e.g. utility invoice or bank receipt)
const nonElectoralOcrText = `
AXIS BANK DEPOSIT SLIP
Account No: 919010023456789
Serial Number: 99882211
Branch: Basirhat
Amount: 5000
`;
const parsedNonElectoral = DocumentTextParser.parse(nonElectoralOcrText, 'bank_statement');
assert(
  parsedNonElectoral.electoral?.electoral_serial_number === undefined,
  "22. Unrelated generic serial number is NOT mapped to electoral_serial_number"
);

// Smart Import normalization & merge
const normalized = DataNormalizer.normalize(parsedVoter);
assert(normalized.electoral_part_number?.value === "142", "DataNormalizer sets electoral_part_number with confidence");
assert(normalized.electoral_serial_number?.value === "587", "DataNormalizer sets electoral_serial_number with confidence");

const job = {
  id: "job-voter-1",
  documentType: "Voter ID",
  provider: "ocr-space" as const,
  source: "file" as const,
  status: "completed" as const,
  version: 1,
  normalizedData: normalized,
};

const merged = MergeEngine.merge([job]);
assert(merged.data.electoral_part_number?.value === "142", "MergeEngine accepts electoral_part_number from Voter ID");
assert(merged.data.electoral_serial_number?.value === "587", "MergeEngine accepts electoral_serial_number from Voter ID");

// Import review flow: leaves status unverified until operator reviews
const autoFillResult = resolveAutoFillPayloadForNewIntake({
  first_name: "Nurul",
  last_name: "Gazi",
  assembly_constituency: merged.data.assembly_constituency?.value,
  assembly_constituency_number: merged.data.assembly_constituency_number?.value,
  electoral_part_number: merged.data.electoral_part_number?.value,
  electoral_serial_number: merged.data.electoral_serial_number?.value,
});

assert(autoFillResult.nextFormValues.electoral_part_number === "142", "Autofill applies Part Number to review");
assert(autoFillResult.nextFormValues.electoral_serial_number === "587", "Autofill applies Serial Number to review");
assert(autoFillResult.nextFormValues.electoral_verification_status === "unverified", "23. Import remains operator-reviewed (status unverified)");
assert(autoFillResult.nextFormValues.electoral_verified_at === null, "Import verified_at is null");

// Field origin protection: user manual entry cannot be overwritten by lookup
const userOrigin: FieldOrigins = {
  electoral_part_number: 'user',
  electoral_serial_number: 'user',
};
const canOverwritePart = canLookupOverwriteElectoralField('electoral_part_number', '999', userOrigin.electoral_part_number);
const canOverwriteSerial = canLookupOverwriteElectoralField('electoral_serial_number', '999', userOrigin.electoral_serial_number);
assert(!canOverwritePart && !canOverwriteSerial, "24. Existing manual value not silently overwritten");

// ==============================================================================
// 7. VERIFICATION (Points 25 - 27)
// ==============================================================================
console.log("\n== SECTION 7: Verification Invariants ==");

const editingCustomer: CustomerFormData = {
  ...createCanonicalEmptyCustomer(),
  electoral_part_number: "200",
  electoral_serial_number: "300",
  electoral_verification_status: "unverified",
  electoral_verified_at: null,
};

assert(editingCustomer.electoral_verification_status === "unverified", "25. Editing Part does NOT set officially_verified");
assert(editingCustomer.electoral_verification_status !== "officially_verified", "26. Editing Serial does NOT set officially_verified");
assert(editingCustomer.electoral_verified_at === null, "27. verified_at is not generated by these edits");

// ==============================================================================
// 8. BACKWARD COMPATIBILITY (Points 28 - 30)
// ==============================================================================
console.log("\n== SECTION 8: Backward Compatibility & Profile Display ==");

// Profile source audit
const profileSource = fs.readFileSync(path.resolve(__dirname, 'src/app/(dashboard)/customers/[id]/page.tsx'), 'utf8');

assert(profileSource.includes("customer.electoral_part_number"), "Profile renders customer.electoral_part_number");
assert(profileSource.includes("customer.electoral_serial_number"), "Profile renders customer.electoral_serial_number");
assert(!profileSource.includes("<p className=\"text-xs sm:text-sm font-medium text-zinc-500\">Parliamentary Constituency</p>"), "Customer profile view no longer shows customer-facing Parliamentary Constituency header");
assert(!profileSource.includes("<p className=\"text-xs sm:text-sm font-medium text-zinc-500\">PC Number</p>"), "Customer profile view no longer shows customer-facing PC Number header");

// Historical customer with PC data loads without crash
const historicalCustomerWithPC: Customer = {
  id: "hist-001",
  first_name: "Legacy",
  middle_name: null,
  last_name: "Customer",
  phone: "+91-9999999999",
  whatsapp: null,
  email: null,
  date_of_birth: null,
  gender: null,
  father_name: null,
  mother_name: null,
  marital_status: null,
  spouse_name: null,
  aadhaar_number: null,
  pan_number: null,
  gst_number: null,
  voter_id_number: null,
  customer_code: "LEG-001",
  assembly_constituency: "Basirhat Dakshin",
  assembly_constituency_number: "126",
  parliamentary_constituency: "Basirhat",
  parliamentary_constituency_number: "18",
  electoral_part_number: null,
  electoral_serial_number: null,
  electoral_verification_status: "unverified",
  electoral_verified_at: null,
  address: "Main Road",
  city: null,
  district: null,
  state: "West Bengal",
  pincode: "743412",
  country: "India",
  photo_url: null,
  photo_source: null,
  original_language_name: null,
  status: "active",
  created_at: "2026-08-01T00:00:00.000Z",
  updated_at: "2026-08-01T00:00:00.000Z",
};

assert(historicalCustomerWithPC.parliamentary_constituency === "Basirhat", "28. Existing customers containing PC data still load without crash");
assert(!migrationContent.includes("DROP COLUMN"), "29. Old PC DB columns are not dropped");

// Extension payload contract test: can still expose all needed fields safely
const apiContract = {
  assembly_constituency: historicalCustomerWithPC.assembly_constituency,
  assembly_constituency_number: historicalCustomerWithPC.assembly_constituency_number,
  electoral_part_number: historicalCustomerWithPC.electoral_part_number,
  electoral_serial_number: historicalCustomerWithPC.electoral_serial_number,
  parliamentary_constituency: historicalCustomerWithPC.parliamentary_constituency,
  parliamentary_constituency_number: historicalCustomerWithPC.parliamentary_constituency_number,
};
assert(apiContract.assembly_constituency === "Basirhat Dakshin", "30. API compatibility preserved");

console.log("\n==========================================================================");
console.log(`TOTAL RESULT: ${passed} PASSED, ${failed} FAILED`);
console.log("==========================================================================");

if (failed > 0) {
  process.exit(1);
}
