"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { BillingEngine } from "@/lib/billing/BillingEngine";
import { InvoiceStatus } from "@/types/billing";

export async function getInvoices(searchQuery?: string, statusFilter?: string) {
  const supabase = await createClient();

  let query = supabase
    .from("invoices")
    .select(`
      *,
      customer:customers(id, first_name, middle_name, last_name, customer_code)
    `)
    .order("created_at", { ascending: false });

  if (statusFilter && statusFilter !== "all") {
    if (statusFilter === "overdue") {
      const today = new Date().toISOString().split("T")[0];
      query = query
        .lt("due_date", today)
        .gt("due_amount", 0)
        .not("status", "in", '("draft","cancelled")');
    } else {
      query = query.eq("status", statusFilter);
    }
  }

  const { data, error } = await query;
  if (error) {
    console.error("Error fetching invoices:", error);
    throw new Error(error.message);
  }

  let filtered = data || [];
  if (searchQuery && searchQuery.trim()) {
    const q = searchQuery.toLowerCase().trim();
    filtered = filtered.filter((inv: any) => {
      const invNum = inv.invoice_number?.toLowerCase() || "";
      const cust = inv.customer;
      const custName = cust
        ? `${cust.first_name || ""} ${cust.middle_name || ""} ${cust.last_name || ""}`.toLowerCase()
        : "";
      const custCode = cust?.customer_code?.toLowerCase() || "";
      return invNum.includes(q) || custName.includes(q) || custCode.includes(q);
    });
  }

  return filtered;
}

export async function getInvoiceById(id: string) {
  const supabase = await createClient();

  const { data: invoice, error: invError } = await supabase
    .from("invoices")
    .select(`
      *,
      customer:customers(id, first_name, middle_name, last_name, customer_code, phone, email),
      items:invoice_items(*)
    `)
    .eq("id", id)
    .single();

  if (invError) {
    console.error("Error fetching invoice by ID:", invError);
    throw new Error(invError.message);
  }

  // Fetch payment allocations for this invoice
  const { data: allocations, error: allocError } = await supabase
    .from("payment_allocations")
    .select(`
      *,
      payment:payments(*)
    `)
    .eq("invoice_id", id)
    .order("created_at", { ascending: false });

  if (allocError) {
    console.error("Error fetching invoice allocations:", allocError);
  }

  return {
    ...invoice,
    allocations: allocations || [],
  };
}

export interface CreateInvoicePayload {
  customer_id: string;
  invoice_date: string;
  due_date?: string | null;
  notes?: string | null;
  status?: 'draft' | 'issued';
  items: Array<{
    service_id?: string | null;
    customer_service_id?: string | null;
    description: string;
    quantity: number;
    unit_price: number;
    discount_amount?: number;
    tax_amount?: number;
  }>;
}

export async function createInvoice(payload: CreateInvoicePayload) {
  const supabase = await createClient();

  if (!payload.customer_id) {
    return { error: "Customer selection is required." };
  }

  if (!payload.items || payload.items.length === 0) {
    return { error: "At least one invoice line item is required." };
  }

  // Calculate snapshot totals using BillingEngine
  const preparedItems = payload.items.map((item) => {
    const qty = Number(item.quantity) > 0 ? Number(item.quantity) : 1;
    const price = Number(item.unit_price) >= 0 ? Number(item.unit_price) : 0;
    const discount = Number(item.discount_amount || 0);
    const tax = Number(item.tax_amount || 0);
    const line_total = BillingEngine.calculateLineTotal({
      quantity: qty,
      unit_price: price,
      discount_amount: discount,
      tax_amount: tax,
    });

    return {
      service_id: item.service_id || null,
      customer_service_id: item.customer_service_id || null,
      description: item.description.trim(),
      quantity: qty,
      unit_price: price,
      discount_amount: discount,
      tax_amount: tax,
      line_total,
    };
  });

  const totals = BillingEngine.calculateInvoiceTotals({
    items: preparedItems as any,
    discount_amount: 0,
    tax_amount: 0,
    paid_amount: 0,
  });

  const initialStatus = payload.status || 'issued';

  const { data: { user } } = await supabase.auth.getUser();

  // Note: invoice_number is generated by DB trigger trg_assign_invoice_number
  // paid_amount defaults to 0, due_amount = total_amount in DB
  const { data: insertedInvoice, error: invInsertError } = await supabase
    .from("invoices")
    .insert([{
      customer_id: payload.customer_id,
      created_by: user?.id || null,
      invoice_date: payload.invoice_date || new Date().toISOString().split("T")[0],
      due_date: payload.due_date || null,
      status: initialStatus,
      subtotal: totals.subtotal,
      discount_amount: totals.discount_amount,
      tax_amount: totals.tax_amount,
      total_amount: totals.total_amount,
      paid_amount: 0,
      due_amount: totals.total_amount,
      notes: payload.notes || null,
    }])
    .select()
    .single();

  if (invInsertError) {
    console.error("Error creating invoice row:", invInsertError);
    return { error: invInsertError.message };
  }

  // Insert invoice items
  const itemsToInsert = preparedItems.map((item) => ({
    invoice_id: insertedInvoice.id,
    customer_service_id: item.customer_service_id,
    service_id: item.service_id,
    description: item.description,
    quantity: item.quantity,
    unit_price: item.unit_price,
    discount_amount: item.discount_amount,
    tax_amount: item.tax_amount,
    line_total: item.line_total,
  }));

  const { error: itemsInsertError } = await supabase
    .from("invoice_items")
    .insert(itemsToInsert);

  if (itemsInsertError) {
    console.error("Error creating invoice items:", itemsInsertError);
    // Cleanup draft invoice row on item failure
    await supabase.from("invoices").delete().eq("id", insertedInvoice.id);
    return { error: itemsInsertError.message };
  }

  revalidatePath("/invoices");
  revalidatePath("/dashboard");
  revalidatePath(`/customers/${payload.customer_id}`);

  return { success: true, data: insertedInvoice };
}

export async function issueInvoice(id: string) {
  const supabase = await createClient();

  const { error } = await supabase
    .from("invoices")
    .update({ status: "issued" })
    .eq("id", id)
    .eq("status", "draft");

  if (error) {
    console.error("Error issuing invoice:", error);
    return { error: error.message };
  }

  revalidatePath(`/invoices/${id}`);
  revalidatePath("/invoices");
  return { success: true };
}

export async function cancelInvoice(id: string) {
  const supabase = await createClient();

  // Check if invoice has payments allocated before cancelling
  const { data: inv } = await supabase
    .from("invoices")
    .select("paid_amount, status")
    .eq("id", id)
    .single();

  if (inv && Number(inv.paid_amount) > 0) {
    return { error: "Cannot cancel an invoice with allocated payments. Void/refund payments first." };
  }

  const { error } = await supabase
    .from("invoices")
    .update({
      status: "cancelled",
      cancelled_at: new Date().toISOString(),
      due_amount: 0,
    })
    .eq("id", id);

  if (error) {
    console.error("Error cancelling invoice:", error);
    return { error: error.message };
  }

  revalidatePath(`/invoices/${id}`);
  revalidatePath("/invoices");
  revalidatePath("/dashboard");
  return { success: true };
}

export async function getCustomerBillingSummary(customerId: string) {
  const supabase = await createClient();

  try {
    const { data: invoices, error: invError } = await supabase
      .from("invoices")
      .select("*")
      .eq("customer_id", customerId)
      .order("created_at", { ascending: false });

    if (invError) throw invError;

    const { data: payments, error: payError } = await supabase
      .from("payments")
      .select("*")
      .eq("customer_id", customerId)
      .order("created_at", { ascending: false });

    if (payError) throw payError;

    const today = new Date().toISOString().split("T")[0];

    const activeInvoices = (invoices || []).filter((inv) => inv.status !== "cancelled");
    const totalBilled = activeInvoices.reduce((sum, inv) => sum + Number(inv.total_amount), 0);
    const totalPaid = activeInvoices.reduce((sum, inv) => sum + Number(inv.paid_amount), 0);
    const outstanding = activeInvoices.reduce((sum, inv) => sum + Number(inv.due_amount), 0);

    const overdue = activeInvoices
      .filter((inv) => inv.due_date && inv.due_date < today && Number(inv.due_amount) > 0 && inv.status !== "draft")
      .reduce((sum, inv) => sum + Number(inv.due_amount), 0);

    return {
      success: true,
      data: {
        totalBilled: BillingEngine.roundMoney(totalBilled),
        totalPaid: BillingEngine.roundMoney(totalPaid),
        outstanding: BillingEngine.roundMoney(outstanding),
        overdue: BillingEngine.roundMoney(overdue),
        invoices: invoices || [],
        payments: payments || [],
      },
    };
  } catch (err: any) {
    console.error("Error fetching customer billing summary:", err);
    return {
      success: false,
      error: err.message || "Failed to load customer billing history.",
      data: {
        totalBilled: 0,
        totalPaid: 0,
        outstanding: 0,
        overdue: 0,
        invoices: [],
        payments: [],
      },
    };
  }
}
